#  ██   █    ██   ▄█▄    █▄▄▄▄ ▄█    ▄▄▄▄▀ ▄▄▄▄▀ ▀▄    ▄
#  █ █  █    █ █  █▀ ▀▄  █  ▄▀ ██ ▀▀▀ █ ▀▀▀ █      █  █
#  █▄▄█ █    █▄▄█ █   ▀  █▀▀▌  ██     █     █       ▀█
#  █  █ ███▄ █  █ █▄  ▄▀ █  █  ▐█    █     █        █
#     █     ▀   █ ▀███▀    █    ▐   ▀     ▀       ▄▀
#    █         █          ▀
#   ▀         ▀

env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 0
    lines: 0

  padding:
    x: 0
    y: 0

  decorations: none

  scrolling:
    multiplier: 1

  opacity: 0.8

font:
  normal:
    family: Iosevka Nerd Font Mono
    style: Regular

  bold:
    family: Iosevka Nerd Font Mono
    style: Bold

  italic:
    family: Iosevka Nerd Font Mono
    style: Italic

  size: 14.0

  offset:
    x: 0
    y: 0

  scale_with_dpi: true

  use_thin_strokes: false

colors:
  primary:
    background: '0x282828'
    foreground: '0xdfbf8e'

  normal:
    black:   '0x665c54'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe78a4e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

  bright:
    black:   '0x928374'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe3a84e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'