right_format = """
$python\
$nodejs\
$package\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
"""
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10
# Disable the blank line at the start of the prompt
add_newline = true

[username]
disabled = false
show_always = true
format = "[](fg:purple)[$user ](bg:purple fg:bold)[at](bg:purple)"

[hostname]
ssh_only = false
format = "[](bg:green fg:purple)[ $hostname](bg:green fg:bold black)"
trim_at = ".companyname.com"
disabled = false

[character]
success_symbol = " [λ](bold burble) "
error_symbol = " [✗](bold red) "

[line_break]
disabled = true

[directory]
disabled = false
truncation_length = 3
truncate_to_repo = true
fish_style_pwd_dir_length = 0
use_logical_path = true
format = "[ ](bg:red fg:green)[$path](bg:red)[](fg:red)"
read_only = "🔒"
read_only_style = "bg:red"

[cmd_duration]
format = "[$duration]($style) "

[status]
disabled = false
format = "[$symbol $status]($style) "
not_found_symbol = ""
not_executable_symbol = ""
sigint_symbol = "ﭦ"
map_symbol = true

[package]
symbol = " "
format = "[ ](bg:blue fg:green)[$symbol$version](bg:green fg:black)"

[git_branch]
format = "[ ](bg:green fg:yellow)[ $symbol$branch](bg:yellow fg:bold black)[](fg:yellow)"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[nodejs]
style = "bg:green fg:black"
format = "[ ](fg:blue)[$symbol$version](bg:blue fg:black)"

[php]
format = "[$symbol($version )]($style)"
symbol = " "

[java]
format = "[${symbol}(${version} )]($style)"
symbol = " "

[rust]
format = "[$symbol($version )]($style)"

[golang]
format = "[$symbol($version )]($style)"
symbol = " "
